### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by AiWABR** [scruffynerf/StashNfoExporterKodi#5]
23-02-22 16:04:30    Error   error executing post hooks: error running plugin: exec: "C:\\Users\\USER\\.stash\\plugins\\StashNfoExporterKodi\\C:\\Users\\USER\\.stash\\plugins\\StashNfoExporterKodi\\C:\\Users\\USER\\.stash\\plugins\\StashNfoExporterKodi\\C:\\Users\\USER\\.stash\\plugins\\StashNfoExporterKodi\\python": file does not exist

How to solve it, can you help me?

Windows 10, stash v0.19.1-24-g2d528733

**Comment by scruffynerf** [comment]
Properly install python for stash.  Not an error with this plugin.
Beyond the level of support I'll do.
